#!/bin/bash

# sh scripts/Autoformer/OpenMIC.sh
# sh scripts/Crossformer/OpenMIC.sh
# sh scripts/DLinear/OpenMIC.sh
# sh scripts/FEDformer/OpenMIC.sh
# sh scripts/FiLM/OpenMIC.sh
# sh scripts/FreTS/OpenMIC.sh
# sh scripts/GRU_D/OpenMIC.sh
# sh scripts/Hi_Patch/OpenMIC.sh
# sh scripts/Informer/OpenMIC.sh
# sh scripts/iTransformer/OpenMIC.sh
# sh scripts/Leddam/OpenMIC.sh
# sh scripts/LightTS/OpenMIC.sh
# sh scripts/Linear/OpenMIC.sh
# sh scripts/MambaSimple/OpenMIC.sh
# sh scripts/MICN/OpenMIC.sh
# sh scripts/mTAN/OpenMIC.sh
# sh scripts/Nonstationary_Transformer/OpenMIC.sh
# sh scripts/PatchTST/OpenMIC.sh
# sh scripts/PrimeNet/OpenMIC.sh
# sh scripts/Pyraformer/OpenMIC.sh
# sh scripts/Raindrop/OpenMIC.sh
# sh scripts/Reformer/OpenMIC.sh
# sh scripts/SeFT/OpenMIC.sh
# sh scripts/SegRNN/OpenMIC.sh
# sh scripts/TiDE/OpenMIC.sh
# sh scripts/TimesNet/OpenMIC.sh
# sh scripts/Transformer/OpenMIC.sh
# sh scripts/TSMixer/OpenMIC.sh
